export const SDK_CAPABILITIES = {
  supportedAuthModes: ["desktop", "service-account"],
  supportedTools: [
    "sdk_capabilities",
    "password_generate",
    "password_generate_memorable",
    "password_read",
    "password_create",
    "password_update",
    "vault_list",
    "vault_get",
    "vault_create",
    "vault_update",
    "vault_delete",
    "group_get",
    "vault_permissions_get",
    "vault_permissions_grant_group",
    "vault_permissions_update_group",
    "vault_permissions_revoke_group",
    "item_search",
    "item_get_metadata",
    "item_create",
    "item_update",
    "item_archive",
    "item_delete",
    "environment_get_variables",
    "environment_get_variable",
    "environment_reveal_variable",
    "secret_reveal",
    "op_script_list",
    "op_script_run",
    "op_session_status",
    "op_session_reset",
  ],
  supportedPrompts: [
    "credential-rotation",
    "vault-audit",
    "environment-inspection",
    "generate-secure-password",
  ],
  supportedResources: [
    "onepassword://config",
    "onepassword://vaults",
    "onepassword://vaults/{vaultId}/items",
    "onepassword://vaults/{vaultId}/items/{itemId}/metadata",
    "onepassword://environments/{environmentId}/variables",
  ],
  unsupportedByOfficialJsSdkBeta: [
    "group_list",
    "group_create",
    "group_members_update",
    "user_list",
    "user_get",
    "user_suspend",
  ],
  notes: [
    "Desktop auth requires the 1Password desktop app beta with SDK integration enabled.",
    "Secrets are opaque by default. Plaintext reveal is disabled unless the server starts with --enable-secret-reveal=true.",
    "Write, destructive, and permission mutation tools are separately gated behind startup flags.",
    "The allowlisted script runner is disabled unless the server starts with --enable-script-runner=true.",
    "The script runner only reads allowlists below configured --script-runner-root paths and withholds stdout/stderr by default.",
    "Vault permission mutation is available only for group-based access because that is the surface exposed by the official JS SDK beta.",
    "1Password Environments are read-only at the moment because the official JS SDK beta only exposes variable retrieval.",
  ],
} as const;
