export const SECRET_REVEAL_ACK = "I_UNDERSTAND_THIS_RETURNS_SECRET_PLAINTEXT";
export const GENERATED_SECRET_ACK =
  "I_UNDERSTAND_THIS_RETURNS_GENERATED_SECRET_PLAINTEXT";
export const DESTRUCTIVE_ACTION_ACK =
  "I_UNDERSTAND_THIS_CAN_DELETE_1PASSWORD_DATA";
export const PERMISSION_MUTATION_ACK =
  "I_UNDERSTAND_THIS_CAN_CHANGE_1PASSWORD_PERMISSIONS";
